### ISSUE TITLE
Wrong date/time in DLQ header after putting messages in DLQ by using rfhutilc

### ISSUE THREAD

**Issue by tadashiok** [ibm-messaging/mq-rfhutil#11]
rfhutilc v9.1.3 Build 230

When getting messages put by rfhutilc from DLQ, by using MQ Explorer for example, the DLH's Date/Time field is not correctly formatted.

**Comment by ibmmqmet** [comment]
fixed 9.1.5

**Comment by tadashiok** [comment]
Great job. Thanks a bunch, Mark!
