### ISSUE TITLE
Segmentation Message Flags

### ISSUE THREAD

**Issue by rkbroder** [ibm-messaging/mq-rfhutil#12]
Please include the following information in your ticket.

- RFHUTIL #4
- amqsbcg output MQ v9. MSGFLAG = 3. In RFHUTIL this shows not segmentation of Segmentation-Allowed

StrucId  : 'MD  '  Version : 2
  Report   : 0  MsgType : 8
  Expiry   : -1  Feedback : 0
  Encoding : 546  CodedCharSetId : 437
  Format : '        '
  Priority : 0  Persistence : 0
  MsgId : X'414D5120424F42424545202020202020C5B4A95F2256533B'
  CorrelId : X'000000000000000000000000000000000000000000000000'
  BackoutCount : 0
  ReplyToQ       : '                                                '
  ReplyToQMgr    : 'BOBBEE                                          '
  ** Identity Context
  UserIdentifier : 'BOBBEEBRODER'
  AccountingToken :
   X'1601050100000034D1FFC9C4D752439394844D5B5D69C200000000000000000C'
  ApplIdentityData : '                                '
  ** Origin Context
  PutApplType    : '11'
  PutApplName    : 'pport Packs\IH03\rfhutil.exe'
  PutDate  : '20201109'    PutTime  : '21323275'
  ApplOriginData : '    '

  GroupId : X'414D5120424F42424545202020202020C5B4A95F22565304'
  MsgSeqNumber   : '1'
  Offset         : '880'
  MsgFlags       : '3'
  OriginalLength : '16'
- Where appropriate, a copy of the message data

**Comment by ibmmqmet** [comment]
Should be fixed in the version that was released over the weekend
