### ISSUE TITLE
mqreply timeout

### ISSUE THREAD

**Issue by al-danilov** [ibm-messaging/mq-rfhutil#14]
Hello!
We with my colleague built mqreply.sh from https://github.com/ibm-messaging/mq-rfhutil/tree/master/mqperf
But we don't suggest that command mqreply has timeout after which process with command is closed.

I attach our file with params for executing mqreply:
> [header]
> qname=DEV.QUEUE.1
> qmgr=QM1
> msgcount=10
> msgtype=2
> format="MQSTR"
> codepage=1208
> persist=0
> replyq=DEV.QUEUE.2
> sleeptime=1000
> maxWaitTime=5
> maxtime=60
> waitTime=60
> replyFilename=/tmp/msqtoload.dat

I try to set maxWaitTime and maxtime, waitTime, but it doesn't affect timeout for life of process.

Can you say how can I let mqreply doesn't close or maybe increase timeout?

Thank you

**Comment by ozyab09** [comment]
The same problem

**Comment by ibmmqmet** [comment]
Use maxReplyTime

**Comment by ibmmqmet** [comment]
v9.1.5 adds maxWaitTime as alias of maxReplyTime
