### ISSUE TITLE
[Simple question] Where do I download the executable?

### ISSUE THREAD

**Issue by manoger** [ibm-messaging/mq-rfhutil#15]
Hello. 👋
I have some questions about this repository.
Does the "mq-rfhutil" have something with the executable "rfhutilc.exe"? 
If "yes", would be possible to make available an executable by a new release?
If "no", can you inform me where do I download? The official sites that I found have broken link. :(

Thanks in advance.

**Comment by ibmmqmet** [comment]
look in the bin/Release directory of this repo

**Comment by manoger** [comment]
Thanks a lot. :)
With the "ih03.pdf" I would be capable to learn more the software and its executables.
About the names "rfhutilc" and "ih03" is an acronym of something?

**Comment by Norbert-Pfister** [comment]
> Thanks a lot. :)
> With the "ih03.pdf" I would be capable to learn more the software and its executables.
> About the names "rfhutilc" and "ih03", is it an acronym of something?

Enjoy the description and history [here in documentation center](https://www.ibm.com/docs/en/ibm-mq/latest?topic=conversion-exchanging-formatted-record-non-jms-application) .
