### ISSUE TITLE
useCSP button missing

### ISSUE THREAD

**Issue by jorsmatthys** [ibm-messaging/mq-rfhutil#17]
Version: 9.1.5 
OS: Windows 10
We requrie the useCSP button to connect with a remote queue manager but it is missing. 

![missing_button_usCSP](https://user-images.githubusercontent.com/67681021/136390635-e2ee8c78-ee77-45ca-a7cf-6feb16a774d5.PNG)

If we try to connect without this option we get: 

14.54.00 2035 Not authorized (Connect)

The documentation included in this release still mentions the useCSP button, so it seems like a bug/regression.

**Comment by ibmmqmet** [comment]
The program now uses CSP always when there's a userid configured as there are no supported versions of MQ that do  not have CSP capability. There's no need for a specific option.

I've just pushed a new version, primarily for TLS currency, but I cleaned up the docs and the code in that area to make it clearer.

**Comment by jorsmatthys** [comment]
Hello,

I believe your changes/cleanup really did fix something regarding the default use of CSP. I just tried the new version you provided and it works perfectly specifying only the userid and password for the remote QM. Doing the exact same thing on 9.1.5 gave me the failure mentionned above. Will this version be added under the release archives instead of 9.1.5 ? 

In any case it works and the doc looks clear to me now, so other than that I consider this resolved :) 
Thanks a lot for looking into this so quickly!
