### ISSUE TITLE
LDAP authentication does not work over secured channel

### ISSUE THREAD

**Issue by mmcg-miked** [ibm-messaging/mq-rfhutil#2]
- mq-rfhutil v9.1.0 Build 227 to queue manager running v9.0.0.3.
- Using rfhutilc and supplying a User id and Password for LDAP authentication over secure channel (Cipher=TLS_RSA_WITH_AES_256_CBC_SHA256) results in the following error in the queue manager logs:

> AMQ9791: The client application did not supply a user ID and password.
> 
> EXPLANATION:
> The client application 'rfhutilc.exe' running on host
> '' did not supply a user ID and password. The
> channel authentication (CHLAUTH) record for the connection requires a user ID
> and password, but none was supplied.

When SSL is disabled on the channel it works.

**Comment by ibmmqmet** [comment]
This should be fixed by build 228. The TLS setting was overriding the way passwords were set.
