### ISSUE TITLE
mTLS not working with RFHUTILC and QMGR

### ISSUE THREAD

**Issue by abudavis** [ibm-messaging/mq-rfhutil#26]
- mq-rfhutilc version: V9.1.3 Build 230
- mq client version:  9.2.0.1
- MQ QMGR version: 9.3.0.4

Trying to enable mutual TLS between RFHUTILC and QMGR but I constantly get the error " SSL unable to initialize - check SSL parms"

Error log on both client and mgr is the same as shown below. The QMGR's certificate has been added to key.kdb file of client and clients certificate has been added to qmgr.

Everything works when SSLCAUTH(OPTIONAL) in the SVRCONN parameters but fails when SSLCAUTH(REQUIRED), any ideas how to resolve this?

`27.04.2023 14:15:24 - Process(23672.1) User(winhell) Program(rfhutilc.exe)
                      Host(RDS10011) Installation(Installation1)
                      VRMF(9.2.0.1)
                      Time(2023-04-27T12:15:24.830Z)
                      RemoteHost(10.244.164.228)
                      CommentInsert1(RFHUTIL.CL01)
                      CommentInsert2(x(xxx))
                     
AMQ9642E: No SSL or TLS certificate for channel 'RFHUTIL.CL01'.

EXPLANATION:
The channel 'RFHUTIL.CL01' did not supply a certificate to use during
SSL or TLS handshaking, but a certificate is required by the remote queue
manager. 

The remote host is 'masked(xxx)'. 

The channel did not start.
ACTION:
Ensure that the key repository of the local queue manager or MQ client contains
a certificate which is associated with the queue manager or client. If you have
configured a certificate label, check that the certificate exists. 

Alternatively, if appropriate, change the remote channel definition so that its
SSLCAUTH attribute is set to OPTIONAL and it has no SSLPEER value set. `

**Comment by Sotyola** [comment]
Unfortunately we have the same issue. Is there any solution or workaround to solve it? 
RfhUtilc: V9.1.6
MQ (Explorer) Client: 9.3.0.0
QMGR: 9.3.0.15

**Comment by abudavis** [comment]
> Unfortunately we have the same issue. Is there any solution or workaround to solve it? RfhUtilc: V9.1.6 MQ (Explorer) Client: 9.3.0.0 QMGR: 9.3.0.15

I fixed this by changing the RFHUTILC's private/personal certificate's label to end with the windows user (without domain) that has started the rfhutilc program `runmqakm -cert -rename -label ibmwebspheremqrfhutil -new_label ibmwebspheremqmyusername -db key.kdb -stashed`

**Comment by Sotyola** [comment]
Thank you! Your solution is working. :)
