### ISSUE TITLE
XML attribute in MQRFH2.usr folder containing a forward slash causes parse error

### ISSUE THREAD

**Issue by mmcg-miked** [ibm-messaging/mq-rfhutil#3]
- v9.1.1 Build 228 

- If the MQRFH2.usr folder contains an XML attribute with a forward slash '/' in the string value then the following error is produced and the usr folder is not displayed:
"XML parse error in usr area - End tag does not match at offset ''"

**Comment by ibmmqmet** [comment]
I just tried to reproduce this and could not. I was able to both create and browse messages where there was a / in a string attribute. It's not clear from the description which operation is causing a problem, or where in the processing that error appears.

Please attach a copy of the message that seems to be problematic - dmpmqmsg format would be good, if you're trying to look at an existing message.

**Comment by mmcg-miked** [comment]
The problem is occurs when reading or browsing the message from the queue. There are no issues when using RFHUtil version V6.0.0 Build 202.

Corporate firewall is preventing me from uploading the file so Im forced to paste it in here - hope that works for you.

```
* DMPMQMSG Version:8.0 Created:Wed Mar  6 09:44:17 2019
* Qmgr  = UKUK_ESB_BKR_D_1
* Queue = MIKE_TEST_Q

A VER 2
A RPT 0
A MST 8
A EXP -1
A FDB 0
A ENC 529
A CCS 1208
A FMT MQHRF2  
A PRI 4
A PER 1
A MSI 414D5120554B554B5F4553425F424B52111A6C5C077BE925
A COI 000000000000000000000000000000000000000000000000
A BOC 0
A RTQ                                                 
A RTM UKUK_ICM_CAL_U_1                                
A USR mqm         
A ACC 16010515000000A837D6657CEB240D235F636B7187010000000000000000000B
A AIX 2020202020202020202020202020202020202020202020202020202020202020
A PAT 11
A PAN \RFHUtil\rfhutilc_v9.1.1.exe
A PTD 20190306
A PTT 09422805
A AOX 20202020
A GRP 000000000000000000000000000000000000000000000000
A MSQ 1
A OFF 0
A MSF 0
A ORL -1
X 5246482000000002000000E400000111000004B82020202020
X 20202000000000000004B8000000203C6D63643E3C4D73643E
X 6A6D735F62797465733C2F4D73643E3C2F6D63643E20000000
X 543C6A6D733E3C4473743E71756575653A2F2F2F4553425F46
X 494C455F534552564943453C2F4473743E3C546D733E313534
X 323838343431323938343C2F546D733E3C446C763E323C2F44
X 6C763E3C2F6A6D733E20000000403C7573723E3C4572726F72
X 3E3C457863657074696F6E20496E73657274733D223132332F
X 223E3C2F457863657074696F6E3E3C2F4572726F723E3C2F75
X 73723E54657374204D6573736167650A


```

**Comment by ibmmqmet** [comment]
Thanks for the message dump. I think I've fixed it now. Looks like it was always a potential problem in the program.

**Comment by mmcg-miked** [comment]
Thank you! usr tab is now displaying correctly
