### ISSUE TITLE
Password is stored in Windows registry in clear text

### ISSUE THREAD

**Issue by isolomatin** [ibm-messaging/mq-rfhutil#4]
Please include the following information in your ticket.

- mq-rfhutil version(s) that are affected by this issue.
Rfhutil v9.1.2.228 (client)
- A small example that demonstrates the issue.
The registry key is shown in the screenshot.
- Where appropriate, a copy of the message data
![rfh](https://user-images.githubusercontent.com/51790628/59438456-8de04300-8dc1-11e9-9269-026bf05c836a.png)

**Comment by ibmmqmet** [comment]
It's beyond the scope of this project to come up with an encryption/obfuscation scheme, or to try to drag in complex prereq components. So the password will no longer be stored at all. The registry key will still exist but will always by empty - that will clean up any already-stored passwords.
