### ISSUE TITLE
does mqput2c (client version) support connection to z/OS qmgr?

### ISSUE THREAD

**Issue by hirschel** [ibm-messaging/mq-rfhutil#6]
Using mqput2c (or mqputsc) and trying to connect to z/OS qmgr, I get mqrc 2058.
mqput2c.c V3.0 Client version
MQSERVER was set correctly.
RFHUTILc is able to connect with the name settings.

Does mqput2c support connecting to a mainframe queue manager?

**Comment by ibmmqmet** [comment]
This repository does not include the *c variants of the mqperf programs, so I don't know where your mqput2c came from. 

The programs here (eg mqput2.exe) can act as either client connected or locally connected. As the **README** says, to force client mode (which may be required if you have the full server product installed)
- Set the MQ_CONNECT_TYPE env var to CLIENT
- Then MQSERVER and CCDTs can be used in the usual way.

**Comment by hirschel** [comment]
(I was using an older version of mqput2 from the last original ih03.) 
The question still stands: Does/should mqput2 support mainframe connections?

MQSERVER=EXPLORER\TCP\sysb.icbc.net(1416)
MQ_CONNECT_TYPE=CLIENT
>C:\IBMUnzip\mq-rfhutil-master\bin\Release\mqput2  -m MQM1 -q TEST -f ./parm.txt
(C) Copyright IBM Corp, 2001 - 2014
mqput2.c V3.0 Release version (Dec 28 2018 07:27:22)

2665 bytes read from data file .\DVB-EZ20002248.XML
Write once switch set - count set to 1
Total files read 1
Total messages found 1

1 messages to be written to queue TEST on queue manager MQM1
minimum queue depth 100 max 1000 batchsize 1
initial sleep time 10 tune = 0
connecting to queue manager MQM1
**MQSeries error with MQCONN on MQM1 - compcode = 2, reason = 2058**

**Comment by ibmmqmet** [comment]
Try changing direction of the slashes in your MQSERVER value.
Connecting to z/os works fine for me.

**Comment by hirschel** [comment]
Bingo, that works! (Staring me right in the face). Thanks Mark.
