### ISSUE TITLE
RFHUTIL - command line

### ISSUE THREAD

**Issue by Rafute** [ibm-messaging/mq-rfhutil#8]
Hi,
This is not an issue but a question.  
Is there a command line version of RFHUTIL?  
When using the PurgeQ selection, the queues are clear quickly.  We've tried using mqqetc and it's very slow getting only 1 messsage at a time.
The queues are approx 20 durable queues that have 10K+ messages to clear.  Clearing them is done manually and would like it automated.

- mq-rfhutil version(s)  is V7.0.2 Build 210

Thank you!

**Comment by ibmmqmet** [comment]
There's no command line variant of rfhutil but when I need to clear a queue then I first try the "CLEAR QLOCAL" MQSC command. That works if noone still has the queue open.

And the dmpmqmsg program that is part of MQ also has a purge option. 
```
dmpmqmsg -m QM1 -p -I <qname>
```

**Comment by Norbert-Pfister** [comment]
Although the [SupportPac MA01](https://www.ibm.com/support/pages/withdrawn-ma01-websphere-mq-q-program) is already withdrawn, it is still usable.
Or you buy the [licensed version](http://www.mqgem.com/q.html) at MQGem.

**Comment by ibmmqmet** [comment]
dmpmqmsg is the productised/supported version of qload that was in MA01

**Comment by Rafute** [comment]
Thank you Mark!  The dmpmqmsg works good.  I’m not sure if it’s the way to use it but I unloaded the messages to a temp file using the -I option.

Thank you,
Alverna

**Comment by Rafute** [comment]
Thank you for your response.  I’ll look up that support pack.

Thank you,
Alverna

**Comment by Vigneshnarayanan** [comment]
> There's no command line variant of rfhutil but when I need to clear a queue then I first try the "CLEAR QLOCAL" MQSC command. That works if noone still has the queue open.
> 
> And the dmpmqmsg program that is part of MQ also has a purge option.
> 
> ```
> dmpmqmsg -m QM1 -p -I <qname> -b 0 
> ```

Is it possible to retain, say last 1000 messages on the queue, archive the rest and send them via an e-mail ?
